# 📘 NumPy Complete Notes

---

## 🔹 Introduction
- **NumPy (Numerical Python)** = High-performance library for numerical computing.  
- Provides:
  - Multidimensional arrays (`ndarray`)
  - Fast mathematical operations
  - Linear algebra, statistics, random number generation

---

## 🔹 Import
```python
import numpy as np

# Creating Numpy Array

In [2]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
#2D and #3D array
b=np.array([[1,2,3],[3,4,6],[2,4,5]])
print(b)

[[1 2 3]
 [3 4 6]
 [2 4 5]]


In [4]:
#3D or Tensor
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
#data type conversion
print(np.array([1,2,3],dtype=float))
print(np.array([0,1,2,4],dtype=bool))#zero = False
print(np.array([2,3,4,5],dtype=complex))

[1. 2. 3.]
[False  True  True  True]
[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [6]:
#np.arange
print(np.arange(1,11))
print(np.arange(1,10,2)) # '2' step 


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [7]:
#with reshape 
print(np.arange(1,7).reshape(3,2))
print(np.arange(1,29).reshape(7,4))

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]]


In [8]:
#np.ones or np.zeros
print(np.ones((3,4)))  #value ko initialse karne ke kaam karne aaata h like in neural networks 
print(np.zeros((8,9)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
print(np.random.random((1,4))) #row or column # range 0 to 1

[[0.85479004 0.82324283 0.83633438 0.45253672]]


In [10]:
#np.linearspace
# 🔹 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
print(np.linspace(1,12,10)) #do distance ke bich ka same distance rkhta h 

[ 1.          2.22222222  3.44444444  4.66666667  5.88888889  7.11111111
  8.33333333  9.55555556 10.77777778 12.        ]


In [60]:
#identity metrics
print(np.identity(3))
print(np.eye(3)) #both are same 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array Atrributes

In [12]:
a1=np.arange(12)
a2=np.arange(12,dtype=float).reshape(2,6)
a3=np.arange(27).reshape(3,3,3) #(box:row:column)
print(a1)
print(a2)


print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [13]:
#ndim no. of dimension - 1d,2d,3d
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [14]:
#shape---> items btata h ki kitne row h kitne column h 
print(a1.shape)
print(a2.shape)
print(a3.shape)

(12,)
(2, 6)
(3, 3, 3)


In [15]:
#size of elememnts in array

print(a3.size)
print(a2.size)
print(a1.size)

27
12
12


In [16]:
#Itemsize in memory --> how much space occupied in memory
a1.itemsize
a2.itemsize
a3.itemsize


8

In [17]:
#dtype
print(a1.dtype)
a2.dtype
a3.dtype

int64


dtype('int64')

# Changing dtype

In [18]:
a3
a3.astype(np.int32) #space reduce hogya q ki instead of 64 humne 32 kar diya 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]], dtype=int32)

# Array Operation

In [19]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
#Scalar operations

#Arithmetic operator

a1+2
a2+2
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
#relational operator
# yeh sab element ko compare karta h un elements se
a1>=5


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
#vector operation --> jab hum do numy arays ke upar operation karte hai jaise ki :
a1/a2
a1*a2
a1+a2
a1-a2


array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

# Array Function

In [23]:
a1=np.random.random((3,3))
a1=np.round(a1*100) #array ko round off karta hai 
a1


array([[82., 54., 33.],
       [26., 81., 30.],
       [38.,  8.,  5.]])

In [24]:
#max/min/sum/prod
#0--> Column #1-> row
print(a1)
# print(a1.max())
# print(a1.min())
# print(a1.sum())
# print(a1.prod())
print(a1.max(axis=1)) #row wise maximum item
print(a1.max(axis=0)) #column wise maximum item

[[82. 54. 33.]
 [26. 81. 30.]
 [38.  8.  5.]]
[82. 81. 38.]
[82. 81. 33.]


In [25]:
#mean / median/std deviation /var
np.mean(a1,axis=1)
np.median(a1,axis=0)
np.std(a1,axis=1)
np.var(a1)

np.float64(693.1111111111111)

In [26]:
#trignometric function
np.sin(a1)

array([[ 0.31322878, -0.55878905,  0.99991186],
       [ 0.76255845, -0.62988799, -0.98803162],
       [ 0.29636858,  0.98935825, -0.95892427]])

In [27]:
# dot product
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)
print(a3.dot(a4))
print(np.dot(a3,a4)) 


[[114 120 126]
 [378 400 422]
 [642 680 718]]
[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [62]:
#log and exponents
print(np.log(a1))
print(np.exp(a1))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]


/var/folders/x6/3z1b_1m13nn8gl_5jykvtxy40000gn/T/ipykernel_976/2230691227.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [66]:
#round / floor / ceil
a5=np.random.random((2,3))*100 #nearest integer pe round off kar deta hai 
print(a5.round())
np.floor(a5)  # ye piche wale pe le jata h jaise 2.16-> 2
np.ceil(a5) #ye aage wale pe 2.34--> 3


[[37. 12. 23.]
 [70. 35. 92.]]


array([[37., 12., 24.],
       [71., 36., 93.]])

In [30]:
#indexing and slicing
a1=np.arange(12)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [31]:
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
#indexing
print(a1[-1]) # negative indexing
print(a1[0])  # posotive slicing 



11
0


In [33]:
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
print(a2[1,2])
print(a2[2,3])
print(a2[1,0])

6
11
4


In [36]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3[1,0,1]
a3[1,1,0]
a3[0,1,1]
a3[0,0,0]

np.int64(0)

In [38]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
print(a1[2:5:2])

[2 4]


In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
print(a2[1:3,1:4])
print(a2[::2,::3])
print(a2[::2,1:4:2])
print(a2[1,::3])
print(a2[:2,1:4])

[[ 5  6  7]
 [ 9 10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [42]:
#3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [44]:

print(a3[::2])
print(a3[0,1,:])
print(a3[1,:,1])
print(a3[2,1::,1::])
print(a3[0::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [45]:
#iterating
a1 #1d me sare elements ko dedeta h 
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [46]:
print(a2)  #har bar ek row print akrta h 
for i in a2:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [47]:
print(a3)
for i in a3:
 print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [48]:
# agar kisi bhi dimension ke array ko access karna hai to hum yeah kar sakte h (nditer)
for i in np.nditer(a3): 
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [49]:
#reshape
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [50]:
#Transpose --> rows column me badal jate h 
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [51]:
#ravel --> kitne bhi dimension ke array ko 1d array me change kar deta h 
a2
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Splitting and Stacking
1. ***Split kya karta h tod deta h aur Stack 2 matrices ko jodta hai***

In [54]:

a9=np.arange(12).reshape(3,4)
a10=np.arange(12,24).reshape(3,4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
#horizontal stacking
np.hstack((a9,a10))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
#vertical stacking
np.vstack((a9,a10))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
a9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
#Horizontal splitting
np.hsplit(a9,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [59]:
#vertical spliiting
np.vsplit(a9,3)


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]