# 📘 NumPy Complete Notes

---

## 🔹 Introduction
- **NumPy (Numerical Python)** = High-performance library for numerical computing.  
- Provides:
  - Multidimensional arrays (`ndarray`)
  - Fast mathematical operations
  - Linear algebra, statistics, random number generation

---

## 🔹 Import
```python
import numpy as np

# Creating Numpy Array

In [ ]:
#np.array
import numpy as np

a=np.array([1,2,3])
print(type(a))

In [ ]:
#2D and #3D array
b=np.array([[1,2,3],[3,4,6],[2,4,5]])
print(b)

In [ ]:
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

In [ ]:
#data type
print(np.array([1,2,3],dtype=float))
print(np.array([0,1,2,4],dtype=bool))#zero = False
print(np.array([2,3,4,5],dtype=complex))

In [ ]:
#np.arange
print(np.arange(1,11))
print(np.arange(1,10,2)) # '2' step 


In [ ]:
#with reshape 
print(np.arange(1,7).reshape(3,2))
print(np.arange(1,29).reshape(7,4))

In [ ]:
#np.ones or np.zeros
print(np.ones((3,4)))  #value ko initialse karne ke kaam karne aaata h
print(np.zeros((8,9)))

In [ ]:
print(np.random.random((1,4))) #row or column

In [ ]:
#np.linearspace
# 🔹 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
print(np.linspace(1,12,10)) #do distance ke bich ka same distance rkhta h 

In [ ]:
#identity metrics
print(np.identity(3))

# Array Atrributes

In [ ]:
a1=np.arange(12)
a2=np.arange(12,dtype=float).reshape(2,6)
a3=np.arange(27).reshape(3,3,3) #(box:row:column)
print(a1)
print(a2)


print(a3)

In [ ]:
#ndim no. of dimension - 1d,2d,3d
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

In [ ]:
#shape---> items btata h ki kitne row h kitne column h 
print(a1.shape)
print(a2.shape)
print(a3.shape)

In [ ]:
#size

print(a3.size)
print(a2.size)
print(a1.size)

In [ ]:
#Itemsize in memory
a1.itemsize
a2.itemsize
a3.itemsize


In [ ]:
#dtype
print(a1.dtype)
a2.dtype
a3.dtype

# Changing dtype

In [ ]:
a3
a3.astype(np.int32) #space reduce hogya q ki instead of 64 humne 32 kar diya 

# Array Operation

In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a2)

In [ ]:
#Scalar operations

#Arithmetic operator

a1+2
a2+2
a1*2

In [ ]:
#relational operator
# yeh sab element ko compare karta h un elements se
a1>=5


In [ ]:
#vector operation --> jab hum do numy arays ke upar operation karte hai jaise ki :
a1/a2
a1*a2
a1+a2
a1-a2


# Array Function

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100) #array ko round off karta hai 
a1


In [ ]:
#max/min/sum/prod
#0--> Column #1-> row
print(a1)
# print(a1.max())
# print(a1.min())
# print(a1.sum())
# print(a1.prod())
print(a1.max(axis=1)) #row wise maximum item
print(a1.max(axis=0)) #column wise maximum item

In [ ]:
#mean / median/std deviation /var
np.mean(a1,axis=1)
np.median(a1,axis=0)
np.std(a1,axis=1)
np.var(a1)

In [ ]:
#trignometric function
np.sin(a1)

In [ ]:
# dot product
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)
print(a3.dot(a4))
print(np.dot(a3,a4)) 


In [ ]:
#log and exponents
np.log(a1)
np.exp(a1)

In [297]:
#round / floor / ceil
a5=np.random.random((2,3))*100 #nearest integer pe round off kar deta hai 
np.floor(a5)  # ye piche wale pe le jata h jaise 2.16-> 2
np.ceil(a5) #ye aage wale pe 2.34--> 3


array([[44., 10.,  4.],
       [35., 49., 75.]])

In [309]:
#indexing and slicing
a1=np.arange(12)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [303]:
print(a1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [305]:
#indexing
print(a1[-1]) # negative indexing
print(a1[0])  # posotive slicing 



11
0


In [306]:
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [310]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [315]:
print(a2[1,2])
print(a2[2,3])
print(a2[1,0])

6
11
4


In [316]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [322]:
a3[1,0,1]
a3[1,1,0]
a3[0,1,1]
a3[0,0,0]

np.int64(0)

In [323]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [326]:
print(a1[2:5:2])

[2 4]


In [327]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [393]:
print(a2[1:3,1:4])
print(a2[::2,::3])
print(a2[::2,1:4:2])
print(a2[1,::3])
print(a2[:2,1:4])

[[ 5  6  7]
 [ 9 10 11]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]


In [394]:
#3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [396]:
a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [412]:

print(a3[::2])
print(a3[0,1,:])
print(a3[1,:,1])
print(a3[2,1::,1::])
print(a3[0::2,0,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[3 4 5]
[10 13 16]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [416]:
#iterating
a1 #1d me sare elements ko dedeta h 
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [419]:
print(a2)  #har bar ek row print akrta h 
for i in a2:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [420]:
print(a3)
for i in a3:
 print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [422]:
# agar kisi bhi dimension ke array ko access karna hai to hum yeah kar sakte h (nditer)
for i in np.nditer(a3): 
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [424]:
#reshape
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [429]:
#Transpose --> rows column me badal jate h 
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [432]:
#ravel --> kitne bhi dimension ke array ko 1d array me change kar deta h 
a2
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
# HOrizontal Stacking

In [ ]:
#vertical Stacking

# Splitting

In [433]:
#horizontal Splitting
a9=np.arange(12).reshape(3,4)
a10=np.arange(12,24).reshape(3,4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [437]:
np.hstack((a9,a10))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [438]:
np.vstack((a9,a10))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [443]:
a9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [442]:
#vertical splitting
np.hsplit(a9,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [444]:
np.vsplit(a9,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]