# 📘 NumPy Bhaichara Guide

**Generated:** 2025-08-18

Ek friendly, Hinglish (bhaichara wali) NumPy guide — explanations + code examples ready to run.

---


## 1. Intro & Setup

NumPy Python ka turbo engine hai numerical computing ke liye. Install via `pip install numpy`. Import convention: `import numpy as np`.


In [ ]:
import numpy as np
np.__version__


**Expected output (approx):**
```
e.g. '1.24.0' (your installed version)
```


## 2. Quick Start — First Array

Arrays lists se zyada efficient hote hain: contiguous memory + vectorized ops.


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))

**Expected output (approx):**
```
[1 2 3] <class 'numpy.ndarray'>
```


## 3. Array Creation Basics

Common constructors: array, asarray, arange, linspace, zeros, ones, full, empty, eye, diag.


In [ ]:
import numpy as np
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.zeros((2,2)))

**Expected output (approx):**
```
arrays printed
```


## 4. Array Attributes

shape, ndim, size, dtype, itemsize batate array ki properties.


In [ ]:
import numpy as np
M = np.arange(12).reshape(3,4)
print(M.shape, M.ndim, M.size, M.dtype, M.itemsize)

**Expected output (approx):**
```
(3,4) 2 12 int64 8
```


## 5. Indexing & Slicing (1D & 2D)

Python-style slicing plus multi-d indexing — powerful for subarrays.


In [ ]:
import numpy as np
x = np.arange(10)
print(x[2:7], x[:5], x[::2])
A = np.arange(12).reshape(3,4)
print(A[1,2], A[:,0])

**Expected output (approx):**
```
sliced arrays
```


## 6. Boolean Masking & Fancy Indexing

Condition se filter karein ya index-list se select karein.


In [ ]:
import numpy as np
x = np.array([10,-5,3,-2,0])
print(x[x<0])
idx=[0,2,4]
print(x[idx])

**Expected output (approx):**
```
[-5 -2] and [10 3 0]
```


## 7. Dtypes & Casting

Dtypes memory aur behavior decide karte hain. astype se cast karein.


In [ ]:
import numpy as np
a = np.array([1,2,3], dtype=np.int32)
print(a.dtype)
b = a.astype(np.float32)
print(b.dtype)

**Expected output (approx):**
```
int32 and float32
```


## 8. Reshape, Views vs Copies

reshape often returns view; flatten always copy; ravel maybe view.


In [ ]:
import numpy as np
z = np.arange(6)
b = z.reshape(2,3)
z[0]=99
print(b)
print(z.ravel().base is z, z.flatten().base)

**Expected output (approx):**
```
view shows change; flatten base is None
```


## 9. Transpose & Axes

T/transpose, swapaxes, moveaxis are used for tensor manipulations.


In [ ]:
import numpy as np
X = np.arange(6).reshape(2,3)
print(X.T.shape)
Y = np.zeros((2,3,4))
print(np.moveaxis(Y,2,0).shape)

**Expected output (approx):**
```
(3,2) and (4,2,3)
```


## 10. Concatenate & Stack / Split

concatenate joins along existing axis; stack adds new axis.


In [ ]:
import numpy as np
a=np.array([1,2]); b=np.array([3,4])
print(np.concatenate([a,b]))
print(np.stack([a,b]).shape)
print(np.array_split(np.arange(10),3))

**Expected output (approx):**
```
joined arrays & split lists
```


## 11. Repeat, Tile, Take, Put

repeat and tile for repeating patterns; take/put for index ops.


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(np.repeat(a,2))
print(np.tile(a,3))
x=np.array([10,20,30,40])
print(np.take(x,[0,3]))
np.put(x,[1,2],[99,88]); print(x)

**Expected output (approx):**
```
repeated and modified arrays
```


## 12. Broadcasting Basics

Shapes are right-aligned; dimensions of size 1 are stretchable.


In [ ]:
import numpy as np
a=np.array([1,2,3])
B=np.array([[10],[20]])
print(a+B)
print((a+B).shape)

**Expected output (approx):**
```
[[11 12 13],[21 22 23]] (2,3)
```


## 13. Ufuncs — Fast Elementwise Ops

ufuncs are vectorized elementwise functions (add, sqrt, exp...).


In [ ]:
import numpy as np
p=np.array([1.,4.,9.])
print(np.sqrt(p))
print(np.add(p,1))

**Expected output (approx):**
```
[1. 2. 3.] and [2. 5. 10.]
```


## 14. Reductions & Accumulate

sum/mean/std etc. axis parameter se control karein.


In [ ]:
import numpy as np
M=np.arange(12).reshape(3,4)
print(M.sum(), M.sum(axis=0))
print(np.cumsum([1,2,3,4]))

**Expected output (approx):**
```
sums and prefix sums
```


## 15. NaN-safe Operations

nanmean/nanstd ignore NaNs for robust stats.


In [ ]:
import numpy as np
x=np.array([1., np.nan, 3.])
print(np.nanmean(x), np.nanmax(x))

**Expected output (approx):**
```
2.0 and 3.0
```


## 16. Comparisons & Logical Ops

logical_and/or/not/xor and where/clip/select for conditionals.


In [ ]:
import numpy as np
u=np.array([-2,-1,0,1,2])
print(np.where(u>0,u,0))
print(np.clip(u,-1,1))

**Expected output (approx):**
```
mapped & clipped array
```


## 17. Searching & Sorting

sort, argsort, searchsorted, partition, unique are helpers.


In [ ]:
import numpy as np
x=np.array([3,1,2])
print(np.sort(x), np.argsort(x))
print(np.searchsorted(np.array([10,20,30]),25))

**Expected output (approx):**
```
[1 2 3], [1 2 0], 2
```


## 18. Set Operations

unique, union1d, intersect1d, setdiff1d, in1d for categorical ops.


In [ ]:
import numpy as np
a=np.array([1,2,2,3]); b=np.array([2,4])
print(np.unique(a), np.union1d(a,b), np.intersect1d(a,b))

**Expected output (approx):**
```
unique and set ops
```


## 19. Random — Generator API

default_rng is recommended for reproducible PRNG.


In [ ]:
import numpy as np
rng = np.random.default_rng(42)
print(rng.integers(0,10,5))
print(rng.normal(size=3))

**Expected output (approx):**
```
random ints and normals
```


## 20. Linear Algebra Basics

dot, matmul (@), einsum, inv, solve, det, eig, svd.


In [ ]:
import numpy as np
A=np.arange(6).reshape(2,3).astype(float)
B=np.arange(6).reshape(3,2).astype(float)
print(A@B)
import numpy.linalg as LA
M=np.array([[3.,2.],[1.,2.]])
print(LA.solve(M, np.array([18.,14.])))

**Expected output (approx):**
```
matrix multiply and solution
```


## 21. Einsum — Powerful Index Notation

einsum expresses contractions clearly and efficiently.


In [ ]:
import numpy as np
A=np.arange(6).reshape(2,3)
B=np.arange(6).reshape(3,2)
print(np.einsum('ij,jk->ik', A, B))

**Expected output (approx):**
```
matrix product
```


## 22. Meshgrid, fromfunction, vectorize

meshgrid for grid evals; fromfunction builds arrays via function.


In [ ]:
import numpy as np
x=np.linspace(-1,1,5); y=np.linspace(-1,1,5)
X,Y=np.meshgrid(x,y)
print(X.shape)
print(np.fromfunction(lambda i,j: i+j, (3,4), dtype=int))

**Expected output (approx):**
```
(5,5) and a 3x4 array
```


## 23. Dates & Times (datetime64)

datetime64 and timedelta64 for vectorized date ops.


In [ ]:
import numpy as np
d = np.array(['2025-08-01','2025-08-15'], dtype='datetime64[D]')
print(d+np.timedelta64(7,'D'))
print(d[1]-d[0])

**Expected output (approx):**
```
dates and timedelta
```


## 24. File I/O — save/load/savez/savetxt/loadtxt, memmap

Binary .npy/.npz are exact; savetxt good for small human files; memmap for huge data.


In [ ]:
import numpy as np
a=np.arange(6)
np.save('tmp_arr.npy', a)
print(np.load('tmp_arr.npy'))

**Expected output (approx):**
```
[0 1 2 3 4 5]
```


## 25. Masked Arrays (numpy.ma)

Masked arrays hide invalid values during computations.


In [ ]:
import numpy as np
import numpy.ma as ma
data=np.array([1,-999,3,-999,5])
md=ma.masked_equal(data,-999)
print(md.mean())

**Expected output (approx):**
```
3.0
```


## 26. Structured Arrays

Heterogeneous columns like mini-database rows.


In [ ]:
import numpy as np
dt=np.dtype([('name','U10'),('age','i4'),('score','f4')])
people=np.array([('Amit',21,88.5),('Neha',23,91.0)], dtype=dt)
print(people['name'])

**Expected output (approx):**
```
['Amit' 'Neha']
```


## 27. FFT (numpy.fft)

Fast Fourier Transform for frequency analysis.


In [ ]:
import numpy as np
sig = np.array([0,1,0,-1])
F = np.fft.fft(sig)
print(np.round(F,3))
print(np.allclose(np.fft.ifft(F), sig))

**Expected output (approx):**
```
spectrum and True
```


## 28. Polynomials (polyfit, polyval)

polyfit for regression, polyval for evaluation.


In [ ]:
import numpy as np
x=np.linspace(0,10,11)
y=3*x+2 + np.random.default_rng(0).normal(scale=0.5,size=len(x))
p = np.polyfit(x,y,1)
print(p)
print(np.polyval(p,5))

**Expected output (approx):**
```
coeffs and prediction
```


## 29. Stride Tricks & Sliding Window (sliding_window_view)

Efficient rolling windows via sliding_window_view.


In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
arr=np.arange(10)
win = sliding_window_view(arr,3)
print(win.shape)
print(win[:4])

**Expected output (approx):**
```
(8,3) and windows printed
```


## 30. Broadcasting Case Study — Image channels

Per-channel bias addition to (H,W,C) image via broadcasting.


In [ ]:
import numpy as np
rng=np.random.default_rng(1)
img = rng.integers(0,256,size=(2,2,3), dtype=np.uint8)
bias = np.array([10,-10,0], dtype=np.int16)
out = np.clip(img.astype(np.int16)+bias,0,255).astype(np.uint8)
print(img)
print(out)

**Expected output (approx):**
```
original and biased images
```


## 31. Performance Tips

Vectorize, prefer views to copies, choose proper dtype, pre-allocate arrays.


In [ ]:
import numpy as np
a = np.ones((1000,1000), dtype=np.float32)
print(a.nbytes/1024/1024, 'MB')

**Expected output (approx):**
```
approx memory in MB
```


## 32. Common Pitfalls

Beware broadcasting mismatches, copy-vs-view, NaNs, axis confusion.


In [ ]:
import numpy as np
print(np.nan == np.nan, np.isnan(np.nan))

**Expected output (approx):**
```
False True
```


## 33. Search & Thresholding Examples

where + boolean masks for threshold-based filtering.


In [ ]:
import numpy as np
rng = np.random.default_rng(2)
a = rng.normal(0,1,10)
mask = np.abs(a)>1
print(a)
print(np.where(mask,a,0))

**Expected output (approx):**
```
array and filtered array
```


## 34. Arg Tricks & unravel_index

argmax/argmin with unravel_index to find positions in flattened arrays.


In [ ]:
import numpy as np
rng = np.random.default_rng(3)
M = rng.integers(0,100,(4,5))
idx = M.argmax()
print(M)
print(np.unravel_index(idx, M.shape))

**Expected output (approx):**
```
matrix and global max pos
```


## 35. Group-like Ops with unique(return_counts)

unique with counts gives simple group-by behaviour.


In [ ]:
import numpy as np
vals=np.array([2,2,3,3,3,5,5,5,5])
u,c = np.unique(vals, return_counts=True)
print(u,c)


**Expected output (approx):**
```
unique values and counts
```


## 36. Mini Projects & Practice ideas

Short project ideas to solidify skills: image ops, Monte Carlo, PCA, rolling stats.


In [ ]:
print('Try: image brightness via broadcasting, Monte Carlo pi, simple PCA via SVD, rolling mean via sliding_window_view')

**Expected output (approx):**
```
list of ideas
```


### Quick Cheat Sheet

Create: array, arange, linspace, zeros, ones, full, empty, eye

Inspect: shape, ndim, size, dtype

Reshape: reshape, ravel, flatten, transpose

Combine: concatenate, stack, vstack, hstack

Math: + - * / **, sqrt, exp, log, sin/cos

Reduce: sum, mean, std, var, cumsum

Random: default_rng, integers, normal, choice

Linalg: dot, matmul, einsum, inv, solve, svd

I/O: save, load, savez, savetxt, memmap
