In [5]:
#np.sort
#return a sorted copy of an array
# numpy.sort(a, axis=1 (row sorting),0 rakhne pe (column sort ), kind=None, order=None) #
import numpy as np
a=np.random.randint(1,100,15)
np.sort(a)



array([17, 26, 27, 32, 38, 44, 51, 59, 67, 71, 72, 75, 83, 83, 89])

In [7]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[61, 77, 10, 46],
       [57,  1, 88, 27],
       [29, 37, 50, 36],
       [ 9, 12, 85, 21],
       [79, 98, 86, 63],
       [95, 87, 49, 35]])

In [11]:
np.sort(b,axis=0) #column sort 

array([[ 9,  1, 10, 21],
       [29, 12, 49, 27],
       [57, 37, 50, 35],
       [61, 77, 85, 36],
       [79, 87, 86, 46],
       [95, 98, 88, 63]])

In [15]:
#descending order me sort karna hai 
np.sort(b)[::-1]

array([[35, 49, 87, 95],
       [63, 79, 86, 98],
       [ 9, 12, 21, 85],
       [29, 36, 37, 50],
       [ 1, 27, 57, 88],
       [10, 46, 61, 77]])

In [18]:
#append
# The numpy.append() appends values along the mentioned axis at the end of the array
np.append(b,200)
np.append(a,27)

array([89, 26, 83, 44, 83, 71, 67, 72, 38, 51, 32, 75, 27, 59, 17, 27])

In [39]:
# np.append(b,np.ones((b.shape[0],1)),axis=1)
print(np.append(b, np.ones((b.shape[0],1)), axis=1))  

[[61. 77. 10. 46.  1.]
 [57.  1. 88. 27.  1.]
 [29. 37. 50. 36.  1.]
 [ 9. 12. 85. 21.  1.]
 [79. 98. 86. 63.  1.]
 [95. 87. 49. 35.  1.]]


In [50]:
#np.concatenate
#2d data ke sath jyada kaam aata h 
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d,),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [53]:
#np.unique
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f=np.array([[1,2,3,1],[1,2,3,2]])

np.unique(e)
np.unique(f)

array([1, 2, 3])

In [63]:
#np.expanddims --> can convert any type array in any dimension
print(a.shape)
print(np.expand_dims(a,axis=0).shape)
print(np.expand_dims(a,axis=1).shape)

(15,)
(1, 15)
(15, 1)


In [66]:
#np.where
# Return the indices of element in input array where the given condition is satisfied 
print(a)
np.where(a>50)


[89 26 83 44 83 71 67 72 38 51 32 75 27 59 17]


(array([ 0,  2,  4,  5,  6,  7,  9, 11, 13]),)

In [68]:
#replace all values > 50 to 0
# np.where(condition,TRue hone pe kya replace karna ,False hone pe kya ??)
print(np.where(a>50,0,a))
#saare even number ko 0 se replace karna h 
print(np.where(a%2==0,0,a))

[ 0 26  0 44  0  0  0  0 38  0 32  0 27  0 17]
[89  0 83  0 83 71 67  0  0 51  0 75 27 59 17]


# np.argmax()
1. # The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [76]:
a=np.random.randint(1,100,24).reshape(4,6)
print(a)
print(np.argmax(a))
print(np.argmin(a))


[[68 59 40 20 12 11]
 [19 14 85  9 22 19]
 [94 41 47 47 45 89]
 [62 70 59 29 96 91]]
[2 3 1 2 3 3]
9


# cumsum
# Return the cumulative sum of the elements along a given axis.

In [79]:
# numpy.cumsum function is used when we want to compute the cumulative sum of array elements over a given axis.
a=np.array([1,2,3,4,5,6,9])
a
np.cumulative_sum(a)
# ye pahle 1 +2 karta h phir 3+3 karta h phir 6+4 
# for example VIRAT KOHLI KA  carreer start run h 0,34,56,33,23,53 to jab woh manle 34 pe tha
#tab uska jo career run kitne the 0+34-->34 cumulative sum
np.cumulative_prod(a) #similar product ke liye 

array([   1,    2,    6,   24,  120,  720, 6480])

In [85]:
#lets try for 2d array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
np.cumulative_prod(b,axis=0) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 24, 36, 50]])

# Numpy.percentile()
1. **numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.**

In [90]:
a
np.percentile(a)

TypeError: percentile() missing 1 required positional argument: 'q'