In [2]:
#np.sort
#return a sorted copy of an array
# numpy.sort(a, axis=1 (row sorting),0 rakhne pe (column sort ), kind=None, order=None) #
import numpy as np
a=np.random.randint(1,100,15)
np.sort(a)



array([ 3,  4, 11, 15, 20, 22, 23, 25, 39, 47, 56, 75, 77, 80, 88])

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[23, 90, 30, 21],
       [58,  5, 54, 25],
       [22, 58, 55, 89],
       [28, 50, 17, 31],
       [92, 90, 56, 51],
       [35, 75, 79, 92]])

In [4]:
np.sort(b,axis=0) #column sort 

array([[22,  5, 17, 21],
       [23, 50, 30, 25],
       [28, 58, 54, 31],
       [35, 75, 55, 51],
       [58, 90, 56, 89],
       [92, 90, 79, 92]])

In [5]:
#descending order me sort karna hai 
np.sort(b)[::-1]

array([[35, 75, 79, 92],
       [51, 56, 90, 92],
       [17, 28, 31, 50],
       [22, 55, 58, 89],
       [ 5, 25, 54, 58],
       [21, 23, 30, 90]])

In [6]:
#append
# The numpy.append() appends values along the mentioned axis at the end of the array
np.append(b,200)
np.append(a,27)

array([20, 23, 80, 56, 25, 88, 15, 75,  4, 22, 47,  3, 11, 39, 77, 27])

In [7]:
# np.append(b,np.ones((b.shape[0],1)),axis=1)
print(np.append(b, np.ones((b.shape[0],1)), axis=1))  

[[23. 90. 30. 21.  1.]
 [58.  5. 54. 25.  1.]
 [22. 58. 55. 89.  1.]
 [28. 50. 17. 31.  1.]
 [92. 90. 56. 51.  1.]
 [35. 75. 79. 92.  1.]]


In [8]:
#np.concatenate
#2d data ke sath jyada kaam aata h 
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d,),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [9]:
#np.unique
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f=np.array([[1,2,3,1],[1,2,3,2]])

np.unique(e)
np.unique(f)

array([1, 2, 3])

In [10]:
#np.expanddims --> can convert any type array in any dimension
print(a.shape)
print(np.expand_dims(a,axis=0).shape)
print(np.expand_dims(a,axis=1).shape)

(15,)
(1, 15)
(15, 1)


In [11]:
#np.where
# Return the indices of element in input array where the given condition is satisfied 
print(a)
np.where(a>50)


[20 23 80 56 25 88 15 75  4 22 47  3 11 39 77]


(array([ 2,  3,  5,  7, 14]),)

In [12]:
#replace all values > 50 to 0
# np.where(condition,TRue hone pe kya replace karna ,False hone pe kya ??)
print(np.where(a>50,0,a))
#saare even number ko 0 se replace karna h 
print(np.where(a%2==0,0,a))

[20 23  0  0 25  0 15  0  4 22 47  3 11 39  0]
[ 0 23  0  0 25  0 15 75  0  0 47  3 11 39 77]


# np.argmax()
1. # The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [13]:
a=np.random.randint(1,100,24).reshape(4,6)
print(a)
print(np.argmax(a))
print(np.argmin(a))


[[ 9 62 37 80 89 10]
 [12 48 94 34 42  7]
 [63 33 51 68 41 85]
 [90 72 55 22 30 54]]
8
11


# cumsum
# Return the cumulative sum of the elements along a given axis.

In [14]:
# numpy.cumsum function is used when we want to compute the cumulative sum of array elements over a given axis.
a=np.array([1,2,3,4,5,6,9])
a
np.cumulative_sum(a)
# ye pahle 1 +2 karta h phir 3+3 karta h phir 6+4 
# for example VIRAT KOHLI KA  carreer start run h 0,34,56,33,23,53 to jab woh manle 34 pe tha
#tab uska jo career run kitne the 0+34-->34 cumulative sum
np.cumulative_prod(a) #similar product ke liye 

array([   1,    2,    6,   24,  120,  720, 6480])

In [15]:
#lets try for 2d array
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
np.cumulative_prod(b,axis=0) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5],
       [ 6, 14, 24, 36, 50]])

# Numpy.percentile()
1. **numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.**

In [40]:
print(a) #jo hundred percent h pure 
np.percentile(a,83.333333333333333) 
np.percentile(a,100)

[1 2 3 4 5 6 9]


np.float64(9.0)

In [41]:
#np.histogram --> frquency count batata h in a given range
# jaise ki koi array h [1,3,13,12,44,21,56,64,4]
a=np.array([1,3,13,12,44,21,56,64,4])
a


array([ 1,  3, 13, 12, 44, 21, 56, 64,  4])

In [51]:

np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])



(array([3, 2, 1, 0, 1, 1, 1, 0, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoeff
*****Return Pearson product-moment correlation coefficients.******

In [52]:
salary = np.array([20000,40000, 25000, 35000, 60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])